sudo: false
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: guhilling-github
    token:
      secure: "t4Z0d6jaGPx86q6ymBCQyyRHGOxQfj30h8JzdItjrBg9AVQ0kgDl63gtoITTV0zFUqXv/324EcxQPL5BKiqzOguXKmQZ2oh9aTwMy7nw9v43g+awu3msZgvX+cN4t5VFpjiGmTBYG3kON4GoqSDlEMeNVaL6X2PU1MRJ3BVgKA/2Ru5BQYUuZn+ajcPqaZzqpTehwHrbkDMb+xTlTz7fS0goXfVO3oR2VWC3pgPiMQ/kepKLLqjWq0tun2BjUEYt2ohG4yyjqo2TByQ2zm4idIhmRmsOVr7ci0WvH9ajx94NsrZyajqPaiybeZAhs5dpXgaCjvrN2U9z6a0amwb+0K0S0yr49xqxmW4w+TMaA/7EfBdqovBhDOU2UkMIVu1ezDtmLQ2PaaYHiabB/DhnlZ2BZaobdlv6yO/LTkQxX1vMBQgNlDLQlgaWPY3mApjRixDTE7KJMtqNIjyHfXEI5bHEejhYy8kns02SBfjKFC6lUdezrdYAycgoZ2uDV1hwPPaFx0KfXujR2OJv+IOEgUxWFXfOUGm3CWS+THnomHFXE8BI0OwuIkFWhA/F9rLYMvnwRH9Hffu1kn9XZiz3wZiq8i9wXxKaB4K2vshgunES8clx26IgKPps959KTTqvjxaRDAEQOXW6IN8bTIB5VT7xmh/HCXhdBI9rzVRP7lY="
    branches:
    - master

language: java

install: "/bin/true"

jdk:
- oraclejdk9

script:
- mvn test jacoco:report sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
