sudo: false
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: literal-generator
    token:
      secure: "RyhED3DMWkT79JJL2jdkmaTPlfQr7+qKIAX9HYkpYN/rTHQyeTAKQoYa3I+Decb18I4bdDTCL7ycweXxK5kzXYBMP04jIIBDTQ7jEFOhr1j0JqYJQ51IWfmfjDForh3lhfBrwvaUmRoV/A6W6oER8LZg0OxSNPVhsBxTZiyoVxdDl0eHZlunD44kLRPRPVC8BQjGanwEU7rKUBc/FEjKrgPztw9VwRvr7drMwr9OK6bRVDw9t90oNoiThipHSTzw2VxXY/OaOfOjYxSoOqIu912CggvkjES2fX7QpZBFf11uAXd5TY7j1YgtNXHexiYdO7TPySQL37gond7b0y3IqpJSwcuptWoXRAzlPmhYcaBdL4NGXT+Q9F35M1SGXJS1qIUTHZn+ffAMdNoiA8a1dZB+K5034qnLIrf4PsCm4UVFwic/rQSw6TzHzSqKisuFNT5vdUo0PqRrZ7WQjHLnDdMFZOjLZMf0qWvII5uC1UtKk5MXjJ0zO+fkCeDw48l9Ier4pI2D44kvwR3DcwHCWgk+Vwm7SWIeOz/r6F89NPkvZDGIe5IFesvc63lnhvAqjeXUuq8Ync1xp68up9gIIUqZJ9Owqd0bFKQ8kifvkZzosii+zdUG1706UD8CuKaCBgoaQZoi5GOaoDv8fyL6d0Ug/KM+Hbi4AlJsCTYCNQ0="
    branches:
    - master

language: java

install: "/bin/true"

jdk:
- oraclejdk9

script:
- mvn test jacoco:report sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
